### ISSUE TITLE
keep Delta_v

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#133]
It has been requested that we keep Delta_v in km/s so that we can recompute the `ZWARN&2**4` flag if need be. @sbailey, do you agree? Ok to call it `DELTAV`?

**Comment by sbailey** [comment]
Quoting myself from an off-list email into this ticket:

In principle we already have the information we need in the minima that are saved in the N best fits in the hdf5 file (i.e. chi2 values and redshifts for the best N fits for each template).  It's just the definition of deltachi2 in zbest that appears confusing because it doesn't include the |dv|<1000 exclusion across template classes.  I'd rather just define deltachi2 as meaning the chi2 difference between minima with |dv|>1000 km/s, since that is the definition of deltachi2 that contributes to the ZWARN flag.  The current definition is just sorting the zall table by chi2 and taking the differences in chi2, which leads to the sort of confusion that started this thread.

I don't think that we can solve this by just including dv in the zbest file, since deltachi2=1 and dv=10 still doesn't tell you what the deltachi2 was for the next best minimum with |dv|>1000 so you'd still have to go to the hdf5 zall table.  Redefining "deltachi2" makes it match the most obvious (?) use case for it (choosing a different threshold for ZWARN), and if someone really does care about deltachi2 values for |dv|<1000 they can still go to the zall table.
