### ISSUE TITLE
zfind.py::zfind() can assign the chi2 curve of another target 

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#138]
When sending `rrboss` with the `targetids` keyword, with targets in decreasing order, we get a different result than if we send in increasing order. This means that `zfind.py::zfind()` mixes lists and dictionary.
You can see that `zz [15] ` are wrongly assigned, producing a difference of `deltachi2` for `TARGETID=7612569720936` between the two runs (see the two `print(zfit)` below).

An easy fix is to be sure that `targets` from `boss.py::read_spectra()` and from `desi.py::DistTargetsDESI()` is sorted by increasing TARGETID, but it seems important to understand what is happening at the `zfind.py::zfind()` level.
 

```
rrboss --spplate $BOSS_SPECTRO_REDUX/v5_10_10/7612/spPlate-7612-56972.fits
--output test.h5
--zbest test.fits
--targetids 7612569720936,7612569720925
```

```
print(zfit)
     chi2               coeff [10]                 z               zerr       zwarn             zz [15]              ... subtype ncoeff    targetid   znum   deltachi2   BRICKNAME
------------- ------------------------------ -------------- ----------------- ----- -------------------------------- ... ------- ------ ------------- ---- ------------- ---------
16661.9705066 2289.78961247 .. 567.744280331 0.104885485403 2.13185052243e-05     0 0.104755218635 .. 0.106282549174 ...             10 7612569720925    0 5447.11538499  7612-569
7488.72770112 559.999868368 .. 214.847865288 0.105109671317 2.92264867668e-05     0 0.103992344284 .. 0.105518620144 ...             10 7612569720936    0 1084.28524739  7612-569

```

 versus

```
rrboss --spplate $BOSS_SPECTRO_REDUX/v5_10_10/7612/spPlate-7612-56972.fits
--output test.h5
--zbest test.fits
--targetids 7612569720925,7612569720936
```

```
print(zfit)
     chi2               coeff [10]                 z               zerr       zwarn             zz [15]              ... subtype ncoeff    targetid   znum   deltachi2   BRICKNAME
------------- ------------------------------ -------------- ----------------- ----- -------------------------------- ... ------- ------ ------------- ---- ------------- ---------
16661.9630917 2289.78582169 .. 567.743768875 0.104885473345 2.13098093104e-05     0 0.103992344284 .. 0.105518620144 ...             10 7612569720925    0 5447.12279989  7612-569
 7488.7272155 559.999713173 .. 214.847838258 0.105109673941 2.92254317271e-05     0 0.104755218635 .. 0.106282549174 ...             10 7612569720936    0 890.059503647  7612-569
```

**Comment by londumas** [comment]
On NERSC, simply do:
```
rrboss --spplate /project/projectdirs/cosmo/data/sdss/dr14/eboss/spectro/redux/v5_10_0/7612/spPlate-7612-56972.fits
--output test_sorted.h5
--zbest test_sorted.fits
--targetids 7612569720925,7612569720936
```
and
```
rrboss --spplate /project/projectdirs/cosmo/data/sdss/dr14/eboss/spectro/redux/v5_10_0/7612/spPlate-7612-56972.fits
--output tes_notsortedt.h5
--zbest test_notsorted.fits
--targetids 7612569720936,7612569720925
```

**Comment by londumas** [comment]
The issue comes from the difference between these two lines:
https://github.com/desihub/redrock/blob/799a598e771035507f98be66264fd1bba0124bc2/py/redrock/zscan.py#L336
https://github.com/desihub/redrock/blob/799a598e771035507f98be66264fd1bba0124bc2/py/redrock/zscan.py#L345

In one the data are sorted by their indices, in the other one the data are given as the dictionary goes.
What is the reason @sbailey for keys to be indices in `zchi2.keys()` and not `TARGETID`?

**Comment by sbailey** [comment]
@londumas thanks for tracking this down.  I agree with your assessment of the bug.  

There is no good reason for the indices vs. keying by TARGETID.  Originally `calc_zchi2_targets` returned the 3 arrays `zchi2`, `zcoeff`, `penalty` which were all in sync with each other, but the major MPI refactor between tags 0.7.0 and 0.8.0 packed these into the `results` dictionary and introduced this bug (now I'm confused why it didn't have much more drastic consequences...).

Updating `zchi2`, `zcoeff`, `penalty` to be dictionaries keyed by TARGETID would be fine.  Note that this also needs to be updated for the MPI case around [lines 269-274](https://github.com/desihub/redrock/blob/799a598e771035507f98be66264fd1bba0124bc2/py/redrock/zscan.py#L269)

Warning: prior to the lines you identified, `zchi2`, `zcoeff`, `penalty` are 

This would have the additional benefit of not packing them into a 2D array just so that they can be unpacked into 1D arrays again for putting into the `results`.

**Comment by londumas** [comment]
@sbailey, ready to be merged. Applyed the correction at the dictionnary level and also by sorting the targetids.
