### ISSUE TITLE
deal with Galactic extinction

### ISSUE THREAD

**Issue by moustakas** [desihub/redrock#158]
I don't believe `redrock` deals with Galactic extinction, but it probably should.

**Comment by moustakas** [comment]
It's because the extinction curve and `Rv`, the total-to-selective extinction ratio, are both *assumed* quantities that in detail vary with Galactic coordinates.  We definitely don't want to lock these assumptions into the DESI spectroscopic data products.

**Comment by kdawson1000** [comment]
I agree with John that the pipeline should report the observed values and let the user perform whatever Galactic extinction correction they think is needed.  However, we do not correct the models in the fitting of BOSS/eBOSS spectra which is crazy.  Also, I am pretty sure that we derived the PCA eigenspectra without any assumption of Galactic absorption.  That is also crazy.  We should change both of these approaches in DESI and be sure to correct the models in the process of fitting.

**Comment by sbailey** [comment]
Galactic extinction code was recently consolidated in `desiutil.dust`, but I would like to keep redrock independent even if that means replicating code in redrock (e.g. so that eBOSS or others using it for non-DESI work don't have to install other desi codes).  

Redrock could have an *optional* dependency on desiutil such that a test would confirm that if desiutil is installed then `redrock.dust` produces the same answer as `desiutil.dust`, but if desiutil isn't installed redrock should continue to work anyway, including just skipping those tests.

**Comment by londumas** [comment]
@sbailey and @moustakas and @kdawson1000, I can take care of that.
However, how can we correct for objects within the Milky-Way, i.e. stars, WD, ...?
Should we apply the full corrections as if all targets were outside the MW?

**Comment by moustakas** [comment]
I'm not sure we've seen the redshift failure rate to really depend on Galactic extinction (@ashleyjross), so this is really only an issue for more detailed astrophysical modeling.
