### ISSUE TITLE
Mg II emission missing from templates

### ISSUE THREAD

**Issue by kdawson1000** [desihub/redrock#177]
As noted in previous discussions, there are a few cases of Mg II emission that are not being modeled in galaxy-like spectra.  For the purposes of future testing of templates, here is a list of cases where there is clear Mg II emission that was not captured by the spectral models.  These are all from LRG targets on tile 68002:

35185929954003617
35185935926691711
35185941924548708
35185941949712672
35185941949713046
35185947922402969
35185965869828931
35185959926497353

**Comment by moustakas** [comment]
@kdawson1000, I'm planning to close this ticket because tile 68002 is from March 2020's SV0 campaign (https://desi.lbl.gov/trac/wiki/SurveyValidation/SV0#ObservedTiles) which is before our date cut-off for processing data (20201214), and consequently, there are no recent reductions I can really look at.

I will say that the Iron/Jura Redrock galaxy templates are known to not include any MgII emission, but that the new galaxy templates (#279) *will* have narrow MgII (to the extent that it's present in the data).
