### ISSUE TITLE
mismatch in template subtype in redrock output files

### ISSUE THREAD

**Issue by sybenzvi** [desihub/redrock#208]
Looking at Fuji-processed data from SV, it seems there is now a mismatch between some template subtypes and the values used in the `Template` objects. In [line 100 of templates.py](https://github.com/desihub/redrock/blob/41bccb33b3fb4a0e3674eeac216054e820eb43a8/py/redrock/templates.py#L100), the subtype for a given spectype defaults to an empty string if it is not specified in the corresponding template in RR_TEMPLATE_DIR. But in new redshift files, unspecified subtypes are set to `MaskedValue` rather than an empty string, producing an error when I try to match the spectype and subtype to a redrock template. This is an issue for the `GALAXY` spectype.

Did something change in the redshift file I/O? Maybe astropy is setting empty strings to MaskedValue automatically?

My workaround is to check for masked subtypes in the redshift files using `numpy.ma.is_masked` and set the subtype to an empty string so I can load the correct template.

**Comment by sbailey** [comment]
This is my least-favorite side-effect of moving to astropy 5: `Table.read()` now auto-masks blank strings and NaN instead of just leaving them as blank strings and NaN, thus breaking previous code like `blat['SUBTYPE'] == ''` (now always False, even when input has blank strings), and `np.isnan(blat['FOO'])` (now always False, even when input on disk has NaN).

This has bitten us several times in desispec, e.g. desihub/desispec#1676 due to NaN masking, and desihub/desispec#1693 due to blank SUBTYPE strings being masked instead of just blank strings.

On the desispec side, we made a wrapper `desispec.io.table.read_table` that loads the data with fitsio, and then casts it into a Table including header keyword propagation.  If you only need the data portion of the table (not the headers), `Table(fitsio.read(filename, ext))` also works without requiring desispec or the other keyword replication logic.

Did you trip on this with user-analysis code parsing redrock output, or something within nightwatch or redrock itself that we should fix?

**Comment by armengau** [comment]
This is also the (only) issue I stumbled on while running prospect on fuji.
The guilty line of code was  `zcat_out.add_row(zcat_in[i_sel])`
which converted RR's subtypes '' to '0.0' 
=> My dirty fix:
```
# zcat_out.add_row seems to convert '' to '0.0' (eg. SUBTYPE) with astropy 5.0 (?)
#   so we use vstack instead
zcat_out = vstack([zcat_out, zcat_in[i_sel]])
```

**Comment by moustakas** [comment]
@sybenzvi please reopen if this is still an issue. FWIW, my standard practice nowadays is to *always* use a `Table(fitsio.read('file.fits'))` combo, even if (perhaps, hopefully) more recent versions of astropy have addressed the feature of forcing masked values on us.
