### ISSUE TITLE
Passing several templates instead of a directory

### ISSUE THREAD

**Issue by echaussidon** [desihub/redrock#213]
Hi, 

With the new qso templates from Alyson, Two templates for quasars are available. How can I run redrock only with these two templates without creating a new directory with only these two templates ?

https://github.com/desihub/redrock/blob/8c31645c4986649156b6de30564a0aba22dca184/py/redrock/external/desi.py#L549

**Comment by sbailey** [comment]
That currently isn't supported, but would be nice to have.  I suggest expanding the `--templates` arg to use `nargs='*'` so that it becomes a list instead of a single entry, and then update [redrock.templates.load_dist_templates](https://github.com/desihub/redrock/blob/8c31645c4986649156b6de30564a0aba22dca184/py/redrock/templates.py#L424) to also accept a list of template files instead of only a single file.  When doing that, maintain backwards compatibility such that the `templates` arg still works as a path or non-list string to a single template.  Note that the initial parsing of `templates` already converts it into a list-of-strings to individual template files in `template_files`, so I think this is just adding another check on the input type of `templates` and handling that.

Note: I suggest *not* making `--templates` a comma separated string to make it easier to use with unix file globs e.g. `rrdesi ... --templates /path/to/templates/rrtemplate-qso*.fits`

**Comment by moustakas** [comment]
This capability is supported in more recent versions of Redrock by passing a text file (with a mandatory `.txt` suffix) with the desired templates, e.g.,
`rrdesi ... --templates=/path/to/templates/mytemplates.txt`

where the `mytemplates.txt` file has, e.g.,
```
rrtemplate-QSO-LOZ-v1.0.fits
rrtemplate-QSO-HIZ-v1.1.fits
```
