### ISSUE TITLE
issue when template file only has one template?

### ISSUE THREAD

**Issue by araichoor** [desihub/redrock#231]
for the desi2 work, I m running redrock with a custom template which includes only one template; admittedly an unusual use of redrock..
with an -- old -- local version of redrock I have (from Apr. 11, 2022), it runs smoothly.
though, when I try with the main version I get this error:
```
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/zfind.py", line 549, in zfind
    ntarg, ncoeff = allzfit['coeff'].shape
ValueError: not enough values to unpack (expected 2, got 1)
```
I ve checked: with `redrock/0.16.0`, it runs ok; so some change in `redrock/0.17.0` may cause that.

I m not familiar with the code, but I m wondering if it could be because my template file only has a single template, and `allzfit['coeff']` happens to just be an array of (ntarg), instead of (ntarg, 1).

or it could be that my template is somewhat ill-formatted; it looks like this:
```
python -c 'from astropy.io import fits; import os; fits.open(os.path.join(os.getenv("RR_TEMPLATE_DIR"), "rrtemplate-lae.fits")).info()'
Filename: /pscratch/sd/r/raichoor/rr-template/rrtemplate-lae.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  BASIS_VECTORS    1 PrimaryHDU      11   (115001, 1)   float64   
  1  REDSHIFTS     1 ImageHDU         7   (52,)   float64   
```

I m just reporting in case of the former.

here is a -- dummy -- example to reproduce the error, with the full log:
```
export RR_TEMPLATE_DIR=$PSCRATCH/rr-template/
rrdesi -i $DESI_ROOT/spectro/redux/iron/healpix/main/backup/0/2/coadd-main-backup-2.fits -o $PSCRATCH/redrock.fits -d $PSCRATCH/rrdetails.h5
Running on a NERSC login node- reducing number of processes to 4
Running with 4 processes
Loading targets...
Read and distribution of 44 targets: 0.2 seconds
DEBUG: Read templates from /pscratch/sd/r/raichoor/rr-template/
DEBUG: Using redshift range 2.3000-2.4996 for rrtemplate-lae.fits
Read and broadcast of 1 templates: 0.0 seconds
Creating GPU context: 0.0 seconds
Rebinning templates: 0.7 seconds
Computing redshifts
  Scanning redshifts for template LAE
/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/lib/python3.9/site-packages/redrock/utils.py:170: RuntimeWarning: A builtin ctypes object gave a PEP3118 format string that does not match its itemsize, so a best-guess will be made of the data type. Newer versions of python may behave correctly.
  nd = np.array(raw, dtype=typecode, copy=False).view()
    Progress:   0 %
    Progress:  10 %
    Progress:  20 %
    Progress:  30 %
    Progress:  40 %
    Progress:  50 %
    Progress:  60 %
    Progress:  70 %
    Progress:  80 %
    Progress:  90 %
    Progress: 100 %
    Finished in: 2.0 seconds
Scanning redshifts: 2.0 seconds
  Finding best fits for template LAE
    Finished in: 1.0 seconds
Finding best redshift: 1.0 seconds
--- Process 0 raised an exception ---
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/lib/python3.9/site-packages/redrock/external/desi.py", line 791, in rrdesi
    scandata, zfit = zfind(targets, dtemplates, mpprocs,
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/lib/python3.9/site-packages/redrock/zfind.py", line 549, in zfind
    ntarg, ncoeff = allzfit['coeff'].shape
Proc 0: ValueError: not enough values to unpack (expected 2, got 1)

Traceback (most recent call last):
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/bin/rrdesi", line 10, in <module>
    desi.rrdesi(comm=None)
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/lib/python3.9/site-packages/redrock/external/desi.py", line 872, in rrdesi
    raise err
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/lib/python3.9/site-packages/redrock/external/desi.py", line 791, in rrdesi
    scandata, zfit = zfind(targets, dtemplates, mpprocs,
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/0.17.0/lib/python3.9/site-packages/redrock/zfind.py", line 549, in zfind
    ntarg, ncoeff = allzfit['coeff'].shape
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by abhi0395** [comment]
I don't know if this issue is resolved? But I just checked with one template (say for galaxies only) and redrock ran without any error:

`rrdesi -i //global/cfs/cdirs/desi/spectro/redux/iron/tiles/cumulative/80606/20201219/coadd-0-80606-thru20201219.fits --templates /global/homes/a/abhijeet/software/desisoft/redrock/py/redrock/templates/rrtemplate-galaxy.fits --targetids 39627646572697743,39627652591519496 -o test.fits -d test.hd5`

So I guess it might be just the issue with fits header of your new-templates?

**Output**
`Finding best redshift: 3.7 seconds
Finalizing results: 0.0 seconds
Computing redshifts: 10.7 seconds
Writing zscan data took: 0.2 seconds
DEBUG: Found 101 archetypes for SPECTYPE GALAXY in file /global/homes/a/abhijeet/software/desisoft/redrock-archetypes/rrarchetype-galaxy.fits
DEBUG: Found 64 archetypes for SPECTYPE QSO in file /global/homes/a/abhijeet/software/desisoft/redrock-archetypes/rrarchetype-qso.fits
DEBUG: Found 40 archetypes for SPECTYPE STAR in file /global/homes/a/abhijeet/software/desisoft/redrock-archetypes/rrarchetype-star.fits
Writing test.fits took: 0.2 seconds
Total run time: 17.5 seconds
(my_software) abhijeet@nid00036:~/test_redrock> srun -N 1 -n 1 --cpu-bind=cores -c 64 rrdesi_mpi -i /global/cfs/cdirs/desi/spectro/redux/iron/tiles/cumulative/80606/20201219/coadd-0-80606-thru20201219.fits --templates /global/homes/a/abhijeet/software/desisoft/redrock/py/redrock/templates/rrtemplate-galaxy.fits --targetids 39627646572697743,39627652591519496 -o test.fits -d test.hd5
Running with 1 processes
Loading targets...
Read and distribution of 2 targets: 0.3 seconds
DEBUG: Using default redshift range -0.0050-1.6997 for rrtemplate-galaxy.fits
Read and broadcast of 1 templates: 0.0 seconds
Creating GPU context: 0.0 seconds
Rebinning templates: 6.0 seconds
Computing redshifts
  Scanning redshifts for template GALAXY
    Progress:   0 %
    Progress: 100 %
    Finished in: 6.9 seconds
Scanning redshifts: 6.9 seconds
  Finding best fits for template GALAXY
    Finished in: 0.5 seconds
Finding best redshift: 0.5 seconds
Finalizing results: 0.0 seconds
Computing redshifts: 7.4 seconds
Writing zscan data took: 0.2 seconds
Writing test.fits took: 0.1 seconds
Total run time: 14.1 seconds
`

**Comment by araichoor** [comment]
I didn t hear back, thanks for looking at that.

one remark though: how many templates has your `rrtempate-galaxy.fits` file? (your file does not have reading permission)
if it s just a copy of the usual one, then it contains several templates.
my case is a single file, with a single template in it; I know it s a peculiar case..

**Comment by araichoor** [comment]
one remark: no urgency on my side on that topic.

**Comment by abhi0395** [comment]
Oh sorry, I misunderstood then, yes redrock template contains 10 templates for galaxies :)

**Comment by abhi0395** [comment]
If it's just one template then, yes this might be an issue (need to be fixed as numpy array manipulation I guess). Anyways, since it's not an urgent issue, I'll get back to it when I have free time!

**Comment by moustakas** [comment]
@araichoor I have a tentative fix for this issue but `/pscratch/sd/r/raichoor/rr-template/` no longer seems to exist. Can you please point me to your 1-galaxy template?

**Comment by araichoor** [comment]
ugh, sorry, it s been deleted.

I ve just copied one template like this at the same location:
```
raichoor@perlmutter:login29:~> echo $PSCRATCH
/pscratch/sd/r/raichoor
raichoor@perlmutter:login29:~> export RR_TEMPLATE_DIR=$PSCRATCH/rr-template/
```

I just tested that the following still crashes as reported above:
```
raichoor@perlmutter:login29:~> rrdesi -i $DESI_ROOT/spectro/redux/iron/healpix/main/backup/0/2/coadd-main-backup-2.fits -o $PSCRATCH/redrock.fits -d $PSCRATCH/rrdetails.h5
```

thanks!

**Comment by moustakas** [comment]
Done in #264.
