### ISSUE TITLE
Large memory footprint when multiprocessing

### ISSUE THREAD

**Issue by ngbusca** [desihub/redrock#35]
Top reports that all subprocesses have the same memory footprint as the main process. redrock is then filling up the memory of my local system (12 cores, 40 GB) when running on a boss plate (~1000 objects, ~4 exposures). I don't have this problem if I set ncpu to 1

Are subprocesses receiving the entire set of data instead of the fraction that the subprocess actually requires? If yes, can this be avoided?

**Comment by ngbusca** [comment]
This gets solved by splitting targets instead or redshift range in the multiprocessing step. Will make this change in the rrboss branch.

**Comment by julienguy** [comment]
Stephen has implemented a shared memory approach when running redrock with multiprocessing.
Maybe you could follow this for rrboss. An alternative is the MPI version that also runs on laptops. This would be useful to have if we plan to run a large BOSS/eBOSS data set at NERSC.

**Comment by sbailey** [comment]
Both the MPI and multiprocessing versions of redrock are using shared memory to not copy all of the read-only input spectra to every process, or at least that is what is supposed to be happening.  I'm not sure how top reports that though; it might be double counting the shared memory.  Is the current state causing a problem (e.g. crashing with a memory error) or is it just that top looks like it is using a lot of memory and you are wondering if that could be optimized?  Could you give examples of your inputs and we could try it at NERSC too?

The calc_zchi2 scan parallelism over redshifts instead of targets was purposeful, since the most expensive step is evaluating the templates at each redshift, which can then be shared for all targets quickly.  Parallelizing that step over targets means that each one has to evaluate each template at every redshift and the performance will likely be much worse.

Details: Earlier versions of redrock relied upon multiprocessing to share memory without copying via POSIX fork "copy on write", but we found that to be problematic when wrapped with Cray MPI.  Sometimes it wouldn't copy the shared memory, and sometimes it would (and then die with out out of memory error).  Since PR #31 (shared memory refactor) I haven't had that problem.

The MPI version also uses shared memory, but we have a problem for large bricks since rank 0 reads everything in and then distributes to shared memory, and rank 0 is exceeding its share of {total_memory} / {number_of_ranks}.  Reading in chunks and distributing should work around that but requires a bit of an I/O refactor...

**Comment by ngbusca** [comment]
But when targets are unpacked, aren't new arrays for flux, etc, being created thus replicating "locally" all the data objects?

**Comment by ngbusca** [comment]
@julienguy  I'm using all the sharedmemory technollogy already developed in redrock, rboss is only a parser to read spCFrames...

**Comment by ngbusca** [comment]
I think this issue was addressed in the latest PR from two days ago. I'd branched from master last week. I'll take a look at the new refactor...

**Comment by ngbusca** [comment]
I checked with the latest master and I still have this problem. Somewhere the individual jobs are copying the full data sample, at least on my computer. I'd be curious to know whether you can reproduce this behavior.

**Comment by ngbusca** [comment]
@sbailey 

> The calc_zchi2 scan parallelism over redshifts instead of targets was purposeful, since the most expensive step is evaluating the templates at each redshift, which can then be shared for all targets quickly. Parallelizing that step over targets means that each one has to evaluate each template at every redshift and the performance will likely be much worse.

I'm not proposing to exchange the orders of the redshift and targets loops (i.e. I propose keep the fact that for each redshift loop over targets). If you keep this ordering, parallelizing over targets means that you move from evaluating each template at each redshift once, to each template at each redshift ncpu times (not ncpu x ntargets) so there isn't much overhead added at this step. If one parallelizes over targets, each worker receives a shorter list of targets (so it needs many less input data).

**Comment by ngbusca** [comment]
fixed in latest master

**Comment by sbailey** [comment]
For the record: @tskisner's work on making the MPI version memory friendly revealed why my multiprocessing shared memory tricks weren't working as well as I had expected: I had converted wave, flux, ivar, and the diagonal format of the resolution matrix to shared memory, but I had forgotten that we also pre-cache a CSR format of the resolution matrix that is much faster for the matrix-matrix multiplies.  The CSR format is actually bigger than the DIA format, and dominates the per-target memory footprint.  Nicolas' fix works around this, but we should consider also spare-matrix-ifying the CSR resolution matrix too...
