### ISSUE TITLE
rrboss doesn't include Fluxcorr nor Fluxdistort when running on individual exposures

### ISSUE THREAD

**Issue by ngbusca** [desihub/redrock#50]
The spCFrames get multiplied by Fluxcorr and Fluxdistort before coaddition. These factors are not currently included in the individual exposures version of rrboss.

**Comment by sbailey** [comment]
spCFrame already have the fluxcorr and fluxdistort terms applied before they are written out so that they are in equivalent units as the coadded spPlate files.  i.e. I don't think you need to do anything here.

Caveat: this is from memory; I'm 99% sure but didn't go back and read the idlspec2d code...

**Comment by ngbusca** [comment]
I looked at idlspec2d yesterday, it also seemed to me that they were already incuded...
