### ISSUE TITLE
Add possibility to add PCA coeff priors

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#56]
In the desi meeting, there was a request to test and add priors to the PCA coefficients

**Comment by sbailey** [comment]
It turns out this was a bad idea for several reasons.  e.g. the plot below shows the c1 vs. c3 galaxy coefficients color coded by redshifts for a test sample.  There are two distinct groups for ELGs and LRGs (and BGS has a third grouping, not shown); they are correlated within a subgroup even if the overall coefficients aren't correlated; and additionally the  coefficient priors would be redshift dependent.  Ugh.

![image](https://user-images.githubusercontent.com/218471/40947516-eb24bd50-6817-11e8-813c-0baca855598b.png)

Augmenting redrock with archetype comparisons at the identified minima and non-negative fits are more promising directions to pursue.  Closing this issue.
