### ISSUE TITLE
Unphysical last value in template

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#62]
All stellar templates have an unphysical last points, see the sharp change at lambda=11,000 A.
This is not very important because there are no or few data there, but it is worth correcting in case one day there is.

![capture d ecran de 2018-01-09 13-09-56](https://user-images.githubusercontent.com/3166436/34740976-67e9f76c-f53e-11e7-947d-0c82a32b4fae.png)

**Comment by sbailey** [comment]
This is probably due to the `desispec.interpolate.resample_flux` edge effects fixed in [desispec PR #415](https://github.com/desihub/desispec/pull/415).  It would probably be easiest to just correct this by hand in the templates files rather than rerunning the template generation with the updated desispec interpolation code.

**Comment by sbailey** [comment]
fixed in redrock-templates 0.4
