### ISSUE TITLE
80 km/s systematic difference between redrock and SDSS-pipeline

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#63]
There is a 80 km/s velocity difference between the redshift of M-star in redrock and the redshift in the eBOSS-pipeline:
![distribution_veliocity_difference](https://user-images.githubusercontent.com/3166436/34743070-b592517e-f545-11e7-90d7-73ae586cc55d.png)

compare K-star templates from eBOSS-pipeline and redrock, the CaII lines agree very well
![compare_template_pipeline_redrock_k](https://user-images.githubusercontent.com/3166436/34742887-0a26c4a0-f545-11e7-8129-33a720ba4e05.png)

compare M-star templates from eBOSS-pipeline and redrock, the CaII lines don't agree.
![compare_template_pipeline_redrock_m](https://user-images.githubusercontent.com/3166436/34742888-0a3ae714-f545-11e7-9170-3cba6256f76f.png)

This can be a feature of redrock/bin/rrstartemplate (but I don't think so), it can also be a feature of desisim.templates.STAR

**Comment by londumas** [comment]
A factor of 0.99973 in wavelength would solve the issue.

**Comment by moustakas** [comment]
Are both wavelength vectors in vacuum wavelengths?  The desisim templates are all vacuum.

**Comment by djschlegel** [comment]
SDSS/BOSS templates have always been in vacuum, since there's otherwise no easy way to redshift them.  It looks like the DESI K-star and M-star templates are inconsistent with one another.  A good sanity test for stellar templates is to fit each using the neighboring stellar class as a template.

**Comment by londumas** [comment]
Thank you for the idea @djschlegel. I tried on one plate that has 174 M-stars. When removing the M-star template, redrock defines all of them as "K". Most importantly, I find a velocity difference of 70 km/s.
So basically in redrock the M and K templates disagree as suggested by the plots above.

**Comment by sbailey** [comment]
This is coming from a wavelength jump vs. TEFF in desispec stellar templates; see desihub/desispec#307.

**Comment by londumas** [comment]
@sbailey, what can be done to fix this?

**Comment by sbailey** [comment]
I don't think this is urgent to fix, so I propose that we wait for @moustakas to fix the TEFF<=3400 stellar templates in desisim and then use that to update the redrock templates via rrstartemplate.

If there is urgency to fix this (e.g. driven by using it for eBOSS) then you could add a special case in rrstartemplate to fix the wavelength solution for any TEFF<=3400 realizations before doing the PCA.  But that is a hack that we'd have to undo once they are fixed in desisim.

Simply fixing the wavelength grid in redrock-templates/rrtemplate-star-M.fits is another option, though note that it was generated with stellar spectra with 3400 <= TEFF <= 3700, which includes one TEFF bin of the correct wavelength solution, so the PCA is contaminated by trying to model a mix of air and vacuum wavelengths.

**Comment by sbailey** [comment]
fixed in redrock-templates 0.4
