### ISSUE TITLE
read SDSS stellar templates

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#66]
The idea is to be able to run on templates from SDSS. The file spEigenStar-55734.fits gives these templates.
A simple code allows to convert these templates into files readabl by redrock.

```
def convert():

    ###
    p = "spEigenStar-55734.fits"
    cat = pyfits.open(p)

    for s in range(123):

        subtype = cat[0].header["NAME"+str(s)].replace(":","")

        ###
        header = fits.Header()
        header['CRVAL1']   = cat[0].header["COEFF0"]
        header['CDELT1']   = cat[0].header["COEFF1"]
        header['LOGLAM']   = 1
        header['RRTYPE']   = 'STAR'
        header['RRSUBTYP'] = subtype
        header['RRVER']    = ""
        header['INSPEC']   = p
        header['EXTNAME']  = "BASIS_VECTORS"

        ###
        hdus = fits.HDUList()
        hdus.append(fits.PrimaryHDU(sp.asarray([cat[0].data[s,:]]), header=header))

        ###
        subtypeWrite = subtype.replace(" ", "").replace("/","")
        outfile = "Templates/rrtemplate-star-"+subtypeWrite+".fits"
        hdus.writeto(outfile, overwrite=True)
        print('RR: Wrote '+outfile)
```

**Comment by londumas** [comment]
@sbailey, the only issue is what to do with ` ` (spaces) `/`, and `:` in their names.
I can leave ` ` in the subtype names, but not in the file name
I can leave `/` in the subtype name, but not in the file name
I can not leave `:` in the subtype name. The reason is that it collids with the basic `type:subtype` format

**Comment by sbailey** [comment]
It looks like you just strip out any ` `(spaces), `/`, and `:`, which seems fine for comparison testing.

However, let's *not* write 123 different star templates into redrock-templates for standard usage.  It would be better to upgrade redrock to support a format like spEigenStar-55734.fits and know how to treat the N>>1 rows as individual templates.  

We might also use a hybrid approach: keep the PCA basis for normal BAFGKM stars, and then include a subset of spEigenStar-55734.fits for the stars that are not well modeled by the PCA.

**Comment by londumas** [comment]
> It looks like you just strip out any (spaces), /, and :, which seems fine for comparison testing.

for testing it works, but I was asking beyond tests

>However, let's not write 123 different star templates into redrock-templates for standard usage. It would >be better to upgrade redrock to support a format like spEigenStar-55734.fits and know how to treat the >N>>1 rows as individual templates.

Why not have 123 templates? It has no impact on the performance and allows not to change anything in the code.

>We might also use a hybrid approach: keep the PCA basis for normal BAFGKM stars, and then include >a subset of spEigenStar-55734.fits for the stars that are not well modeled by the PCA.

My goal is to separate the problem. The templates formating on one side and the redshift calculation on the other.
For the redshift calculation, I want to add a condition: if there is only one vector, then it solves the redshift linearly.

**Comment by sbailey** [comment]
It just seems like clutter to have N>>1 files with one archetype[*] template each, when we have an example of a format for grouping N>>1 related archetype templates into a single file.  We can still maintain the distinction between template formatting vs. redshift fitting; I'm just suggesting to support two input template formats instead of just one.

+1 for adding the special case of fitting a single vector, instead of setting up a bunch of linear algebra that ends up solving a 1 x 1 matrix to get that one scaling coefficient.

[*] By "archetype" I mean a single vector template rather than a set of basis vectors to be fit in a linear combination.

**Comment by londumas** [comment]
@sbailey, ok. I will take care of this.
Still I will need to change the spEigenStar-55734.fits file to change the names of variables, to be the same as in redrock. Like CRVAL1, CDELT1, LOGLAM, RRTYPE.
Do you agree ?

**Comment by sbailey** [comment]
Yes, that is fine.  We don't have to support the exact spEigenStar-55734.fits format, as long as we have something conceptually similar (and +1 for posting the code for converting between them).  Thanks for working on this.

**Comment by londumas** [comment]
@sbailey, something I didn't understand is if we should fit a_0*Template(lambda). Or don't fit at all for a scalar and just scan the redshift.

**Comment by sbailey** [comment]
Yes @londumas we should fit for the scale factor at each redshift.  When there is only a single scale factor instead of a set of coefficients, the linear algebra reduces to:

a = dot(data, template) / dot(template, template)

where template = the template shifted to the desired redshift and resampled to the data wavelength grid.

**Comment by londumas** [comment]
In redrock/py/redrock/zscan.py, we get the parameters with ` a = np.linalg.solve(M, y)`. When there is only one vector, we could do `a = (y*M).sum()/(M*M).sum()`. But for some reasons this last piece of code is way slower than the first one. Any idea why?

**Comment by sbailey** [comment]
Good that you checked the speed instead of just assuming that it would be faster (i.e. don't believe everything I suggest in a github issue...).  It might have to do with the intermediate arrays created in python vs. directly making a class to some MKL optimized compiled code for `np.linalg.solve`.  You might get better performance with `a = np.dot(M, y) / np.dot(M, M)` (that might need some update to handle `M` 2D -> 1D).

If we do add a special case for a single template, it should be more than just replacing `a = np.linalg.solve(M, y)`.  The lines of code right before that for setting up `M` could also be simplified, maybe with some speed gain.

Don't spend too much time on this.  If treating this as a special case is only a small speed gain or big if/then code mess, don't bother.  OK to proceed with the I/O wrappers for the new archetype template format without optimizing this piece yet.

**Comment by sbailey** [comment]
Utility code was added in PR #78 for converting SDSS templates into redrock format, but let's leave this open until we know how many we need to add and have added them to redrock-templates (or otherwise refactored the format if we need to add more than 5 of them).

**Comment by londumas** [comment]
In order to know if we need to add SDSS stellar templates I ran redrock with its current templates adding also the 123 SDSS stellar templates. The results show that with the current redrock (i.e. no broadbands) we have that only `0.03%` of redrock galaxies are stars.
The few exemples are are in very few cathegories: `['LDWARF' 'CARBON' 'WDCOOLER']`.
This number would change when adding broadbands to redrock.

Thus currently we would just have to add these three SDSS templates

Here are the objects:
https://dr14.sdss.org/optical/spectrum/view?plate=3761&mjd=55272&fiberid=538
https://dr14.sdss.org/optical/spectrum/view?plate=3783&mjd=55246&fiberid=706
https://dr14.sdss.org/optical/spectrum/view?plate=3861&mjd=55274&fiberid=652
https://dr14.sdss.org/optical/spectrum/view?plate=3861&mjd=55274&fiberid=712
https://dr14.sdss.org/optical/spectrum/view?plate=4045&mjd=55622&fiberid=774
https://dr14.sdss.org/optical/spectrum/view?plate=4443&mjd=55539&fiberid=454
https://dr14.sdss.org/optical/spectrum/view?plate=4852&mjd=55689&fiberid=530
https://dr14.sdss.org/optical/spectrum/view?plate=4865&mjd=55713&fiberid=828
```
                              redrock+SDSS stellar templates
current redrock
                           ||            || STAR      || GALAXY || QSO      || 
                           || STAR       || 100.0%    || 0.0%   || 0.0%     || 
                           || GALAXY     || 0.03%     || 99.96% || 0.0%     || 
                           || QSO        || 0.0%      || 0.0%   || 100.0%   || 

```

**Comment by sbailey** [comment]
Go ahead and add LDWARF and CARBON to redrock-templates.

Let's try doing a WD PCA based upon our WD templates.  That should work for WDCOOLER while also working for other WD stars.  That shouldn't be a blocking factor for adding LDWARF and CARBON, and if the WD PCA doesn't work so well we can always add WDCOOLER later.

**Comment by sbailey** [comment]
PR #101 wraps this up.  Closing.
