### ISSUE TITLE
Tutorial is broken

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#81]
The following tutorial is broken because `redrock.io` doesn't exist anymore
https://github.com/desihub/tutorials/blob/master/redrock/RedrockBOSSDemo.ipynb

**Comment by londumas** [comment]
One example solution is:
```
import redrock.results
import redrock.templates
lstFiles = redrock.templates.find_templates(templates)
templates = {}
for el in lstFiles:
    t = redrock.templates.Template(filename=el)
    templates[t.full_type] = t

zscan, zfit = redrock.results.read_zscan(rrfile)
```

**Comment by sbailey** [comment]
Let's restore the equivalent of `redrock.io.read_templates()`, possibly as `redrock.templates.read_templates()` instead of adding that code to the tutorial itself.

**Comment by lwymarie** [comment]
I'm new to redrock. I have a similar problem. 

Using the latest zfind function requires a DistTargets object and a DistTemplate object. I created the DistTargets object using redrock.targets.DistTargets('my-galaxy-id'), but I do not know how to create the DistTemplate object. Specifically, I do not know how to create the dwave dictionary because I do not know how to create the dictionary keys 'wavehash.'

May I ask about the progress of restoring redrock.io.read_templates? Meanwhile, how do I make use of the above example solution? It does not show how rrfile is created.

**Comment by londumas** [comment]
@lwymarie, could you have a look at rrplot?
Just run in a `ipython --pyplot`:
`%run rrplot <arguments>`

**Comment by lwymarie** [comment]
I'm able to locate the rrplot script, but I don't quite get how that could help? 

I'd like to run the following that used to work in release v0.4.1: 
zscan, zfit = zfind([rrTargObj], [galTemp]) , where I give a Target object and a Template object as input. 

However, in the latest release, rrTargObj takes a distTargets object and a DistTemplate object, and I don't know how to create them.

**Comment by lwymarie** [comment]
I added some kludges following demonstrations in the test module. Problem solved. Thanks.

**Comment by londumas** [comment]
Tested running https://github.com/desihub/tutorials/blob/master/redrock/RedrockBOSSDemo.ipynb and works fine, i.e. issue fixed.
