### ISSUE TITLE
Definition of `ZERR` when multiple minima within 1000 km/s

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#96]
The current definition of `ZERR` is given by a parabola fit at the minimum.
When the fit present multiple minima within 1000 km/s, only the deepest is defined as the minimum.
In this case, the definition of the error could/should be different.
Is there a case where we would need a good estimation of the redshift error? Do people use this field for anything?
If it is important we could add a `DELTAZ` entry giving `0` if there is only one minimum and giving `max(|DELTAZ|)` if there are more than one.

**Comment by sbailey** [comment]
Opinion: ZERR is an approximation of the true uncertainty, since it is parameterizing a non-Gaussian likelihood with a single Gaussian sigma (or equivalently, a parabola fit in chi2).  Having multiple local minima within the fitted error of the deepest minima is a special case of that.  I don't think we should put too much effort into addressing these special cases as long as (z - truez)/zerr is approximately Gaussian with mean=0 sigma=1.  Analyses that need more detail are probably best served by using the original chi2 vs. z curve instead of a tweaked version of a single parameter ZERR.

Other opinions?

**Comment by londumas** [comment]
ok.
